---
title: "Study_2"
output: html_document
date: "2025-04-02"
---

```{r setup and clean}

#install.packages(c("readxl", "psych", "car"))
#install.packages("tidyverse")

# Load libraries
library(tidyverse)
library(readxl)
library(psych)
library(car)
library(readr)
library(dplyr)
remove.packages("plyr")

#Study2 <- read.csv("~/Downloads/Study 2_March 30, 2025_09.37.csv")
Study2 <- read_csv("~/Downloads/Study 2_March 30, 2025_09.37.csv", 
    skip = 2)

names(Study2) <-  c("StartDate" , "EndDate",                "Status" ,                "IPAddress"  ,            "Progress", "Duration..in.seconds.",  "Finished"   ,            "RecordedDate"  ,         "ResponseId"  ,           "RecipientLastName"    , 
 "RecipientFirstName"  ,   "RecipientEmail"  ,       "ExternalReference"   ,   "LocationLatitude" ,      "LocationLongitude"   ,  
 "DistributionChannel"  ,  "UserLanguage"     ,      "consent"   ,             "ProlificID"   ,          "HS"       ,             
"RH.S"       ,            "HO"      ,               "RH.O"      ,             "scale.1"      ,          "scale.2"  ,             
 "scale.3"    ,            "scale.4"    ,            "scale.5"    ,            "explain.1"     ,         "explain.2"  ,            "Basic.Q1"     ,          "Basic.Q1_4_TEXT"   ,     "Basic.Q2"      ,         "Basic.Q3"    ,           "Basic.Q3_8_TEXT"    ,   
"Cultural.demo",          "Religion.belief.Q1"    , "Religion.belief.Q2" ,    "Religion.belief.Q3"  ,   "Religion.belief.Q4"    ,
"Self.harm.experience",   "Self.harm.experience.1", "Self.harm.experience.2")


colSums(is.na(Study2))
nrow(Study2)

Study2_clean <- Study2 %>%
  filter(!is.na(`scale.5`))

nrow(Study2_clean)

Study2_clean_regression <- Study2_clean %>% 
  mutate(
    scale.1 = as.numeric( scale.1),
    scale.2 = as.numeric( scale.2),
    scale.3 = as.numeric( scale.3),
    scale.4 = as.numeric( scale.4),
    scale.5 = as.numeric( scale.5),
    Religion.belief.Q1 = as.numeric(`Religion.belief.Q1`), # 1–4 scale
    Self.harm.experience = as.numeric(`Self.harm.experience`) # 1 = yes, 2 = no
  ) %>%
  filter(
    !is.na(Self.harm.experience),
    Self.harm.experience %in% c(1, 2)  # remove "prefer not to say"
  )

library(tidyverse)

# Save the cleaned data to your computer
write_csv(Study2_clean, "Study2_clean.csv")

write_csv(Study2_clean, "/Users/zili/Downloads/Study2_clean.csv")

```



```{r check and run regression}
# check if religion and self-harm experience predicted moral wrongness rating, if it does, control them. 
model <- lm(scale.5 ~ Religion.belief.Q1 + Self.harm.experience, data = Study2_clean_regression) 

# install.packages("lm.beta")
library(lm.beta)
lm.beta(model)
summary(model)
# predicting moral wrongness ratings (scale.5) using two predictors
#Religion.belief.Q1 (self-rated religiosity, 1 = not at all, 4 = very religious); Self.harm.experience (1 = yes, 2 = no)



# since religiosity significant predict moral judgment, I control that when run my later regression analysis. 
# ⬇️


# regression and controlling for religion. 
model <- lm(scale.5 ~ scale.1 + scale.2.rev + scale.3 + scale.4.rev + Religion.belief.Q1,
            data = Study2_clean)

summary(model)
vif(model)

# using the total scale for self and harm; to predict scale.5 while control the religion belief. 
Study2_clean <- Study2_clean %>%
  mutate(Total_S = (scale.1 + scale.2.rev) / 2)

Study2_clean <- Study2_clean %>%
  mutate(Total_O = (scale.3 + scale.4.rev) / 2)

model <- lm(scale.5 ~ Total_S + Total_O + Religion.belief.Q1,
            data = Study2_clean)
lm.beta(model)
summary(model)


# install.packages("sjPlot")
library(sjPlot)
tab_model(model)

```

```{r two way ANOVA}

# a new column identifying the condition based on which manipulation column has a response.

names(Study2_clean)

# install.packages("writexl")  
# library(writexl)
# write_xlsx(Study2_clean, path = "/Users/zili/Downloads/Study2_clean.xlsx")


# Create SelfOthers and HarmType columns
Study2_clean <- Study2_clean %>%
  mutate(
    SelfOthers = case_when(
      !is.na(HS) ~ 1,         # Harm to self
      !is.na(`RH.S`) ~ 1,     # Reduce harm to self
      !is.na(HO) ~ 2,         # Harm to others
      !is.na(`RH.O`) ~ 2,     # Reduce harm to others
      TRUE ~ NA_real_
    ),
    HarmType = case_when(
      !is.na(HS) ~ 2,         # Causing harm
      !is.na(HO) ~ 2,         # Causing harm
      !is.na(`RH.S`) ~ 1,     # Reducing harm
      !is.na(`RH.O`) ~ 1,     # Reducing harm
      TRUE ~ NA_real_
    )
  )

# create two columns, self & others. 
Study2_clean <- Study2_clean %>%
  mutate(Self = case_when(
    !is.na(`RH.S`) ~ 1,     # Reducing harm to self
    !is.na(HS) ~ 2,         # Causing harm to self
    TRUE ~ NA_real_
  ))

# Add Other column: 1 = Reduce Harm to Others, 2 = Cause Harm to Others
Study2_clean <- Study2_clean %>%
  mutate(Other = case_when(
    !is.na(`RH.O`) ~ 1,     # Reducing harm to others
    !is.na(HO) ~ 2,         # Causing harm to others
    TRUE ~ NA_real_
  ))

# NEW! manipulation check

t.test(Total_S ~ Self, data = Study2_clean)

t.test(Total_O ~ Other, data = Study2_clean)


# get the SD
Study2_clean %>%
  group_by(Self) %>%
  summarise(
    Mean = mean(Total_S, na.rm = TRUE),
    SD = sd(Total_S, na.rm = TRUE),
    N = n()
  )

# the SD for Others
Study2_clean %>%
  group_by(Other) %>%
  summarise(
    Mean = mean(Total_O, na.rm = TRUE),
    SD = sd(Total_O, na.rm = TRUE),
    N = n()
  )

# reverse code.
Study2_clean <- Study2_clean %>%
  mutate(
    scale.2.rev = 8 - scale.2,  # reverse code scale 2
    scale.4.rev = 8 - scale.4   # reverse code scale 4
  )

Study2_clean <- Study2_clean %>%
  mutate(
    scale.5.rev = 10 - scale.5,  # reverse code scale 5
  )




```


```{r}
# run two-way ANOVA

# make sure my IV is factors. 
Study2_clean$SelfOthers <- as.factor(Study2_clean$SelfOthers)
Study2_clean$HarmType <- as.factor(Study2_clean$HarmType)

Study2_clean$Religion.belief.Q1 <- as.numeric(Study2_clean$Religion.belief.Q1) # control it, since it's significantly predict my dv. 

# Set contrasts for categorical variables (this is critical!)
# Type III SS requires sum contrasts, not the default treatment contrasts.

contrasts(Study2_clean$SelfOthers) <- contr.sum(2)
contrasts(Study2_clean$HarmType) <- contr.sum(2)

# Run ANCOVA
# ancova_model <- aov(scale.5 ~ SelfOthers * HarmType + Religion.belief.Q1, data = Study2_clean)
# above one use type=1; not the ideal method for my situation, so change to type=3

model_lm <- lm(scale.5 ~ SelfOthers * HarmType + Religion.belief.Q1, data = Study2_clean)
Anova(model_lm, type = 3)

summary(model_lm )

interaction.plot(x.factor = Study2_clean$SelfOthers,
                 trace.factor = Study2_clean$HarmType,
                 response = Study2_clean$scale.5,
                 fun = mean,
                 type = "b",
                 col = c("blue", "red"),
                 pch = c(16, 17),
                 xlab = "Self vs Others",
                 ylab = "Moral Rating",
                 trace.label = "Harm Type")

library(ggplot2)

Study2_clean$SelfOthers <- as.factor(Study2_clean$SelfOthers)
Study2_clean$HarmType <- as.factor(Study2_clean$HarmType)


# plot?
# install.packages("ggpubr")
library(ggpubr)

Study2_clean$SelfOthers <- factor(Study2_clean$SelfOthers,
                                  levels = c(1, 2),
                                  labels = c("Self", "Others"))

Study2_clean$HarmType <- factor(Study2_clean$HarmType,
                                levels = c(1, 2),
                                labels = c("Reducing Harm", "Causing Harm"))

summary_data <- Study2_clean %>%
  group_by(SelfOthers, HarmType) %>%
  summarise(
    mean = mean(scale.5, na.rm = TRUE),
    sd = sd(scale.5, na.rm = TRUE),
    n = sum(!is.na(scale.5)),
    se = sd / sqrt(n),
    .groups = "drop"
  )
ggbarplot(
  data = Study2_clean,
  x = "SelfOthers",         
  y = "scale.5", # DV
  fill = "HarmType", # group color
  add = "mean_se",   # add error bars (mean ± SE)
  position = position_dodge(),
  palette = "jco"          
) + 
  labs(
    x = "Target of Harm",
    y = "Moral Wrongness Rating"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "right") +
  coord_cartesian(ylim=c(1,9)) +
  scale_y_continuous(breaks = seq(1,9,1))


# plot sec try
# for harm type
harmtype_summary <- Study2_clean %>%
  group_by(HarmType) %>%
  summarise(
    mean = mean(scale.5, na.rm = TRUE),
    sd = sd(scale.5, na.rm = TRUE),
    n = sum(!is.na(scale.5)),
    se = sd / sqrt(n)
  )
ggplot(harmtype_summary, aes(x = HarmType, y = mean, fill = HarmType)) +
  geom_bar(stat = "identity", width = 0.6, color = "black") +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  labs(
    x = "Harm Type",
    y = "Moral Wrongness Rating",
    title = "Main Effect of Harm Type on Moral Judgments"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")+
  coord_cartesian(ylim=c(1,9)) +
  scale_y_continuous(breaks = seq(1,9,1))


# for target
selfother_summary <- Study2_clean %>%
  group_by(SelfOthers) %>%
  summarise(
    mean = mean(scale.5, na.rm = TRUE),
    sd = sd(scale.5, na.rm = TRUE),
    n = sum(!is.na(scale.5)),
    se = sd / sqrt(n)
  )
ggplot(selfother_summary, aes(x = SelfOthers, y = mean, fill = SelfOthers)) +
  geom_bar(stat = "identity", width = 0.6, color = "black") +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) + 
  labs(
    x = "Self Others",
    y = "Moral Wrongness Rating",
    title = "Main Effect of target on Moral Judgments"
  ) 
  # theme_minimal(base_size = 14) +
 # theme(legend.position = "none")

```



```{r manipulation check}

# the scale answers they gave might have changed depending on which questions participants saw. That was the point of my manipulation.In another words: how about we take look at their perceived harm.
summary(aov(scale.1 ~ SelfOthers * HarmType, data = Study2_clean))
Study2_clean %>%
  group_by(SelfOthers, HarmType) %>%
  summarise(
    Mean = mean(scale.1, na.rm = TRUE),
    SD = sd(scale.1, na.rm = TRUE),
    n = n()
  )

interaction.plot(x.factor = Study2_clean$SelfOthers,
                 trace.factor = Study2_clean$HarmType,
                 response = Study2_clean$scale.1,
                 fun = mean,
                 type = "b",
                 col = c("blue", "red"),
                 pch = c(16, 17),
                 xlab = "Self vs Others",
                 ylab = "cause harm to self",
                 trace.label = "Harm Type")

summary(aov(scale.2 ~ SelfOthers * HarmType, data = Study2_clean))
Study2_clean %>%
  group_by(SelfOthers, HarmType) %>%
  summarise(
    Mean = mean(scale.2, na.rm = TRUE),
    SD = sd(scale.2, na.rm = TRUE),
    n = n()
  )
interaction.plot(x.factor = Study2_clean$SelfOthers,
                 trace.factor = Study2_clean$HarmType,
                 response = Study2_clean$scale.2,
                 fun = mean,
                 type = "b",
                 col = c("blue", "red"),
                 pch = c(16, 17),
                 xlab = "Self vs Others",
                 ylab = "scale.2",
                 trace.label = "Harm Type")

summary(aov(scale.3 ~ SelfOthers * HarmType, data = Study2_clean))
Study2_clean %>%
  group_by(SelfOthers, HarmType) %>%
  summarise(
    Mean = mean(scale.3, na.rm = TRUE),
    SD = sd(scale.3, na.rm = TRUE),
    n = n()
  )
interaction.plot(x.factor = Study2_clean$SelfOthers,
                 trace.factor = Study2_clean$HarmType,
                 response = Study2_clean$scale.3,
                 fun = mean,
                 type = "b",
                 col = c("blue", "red"),
                 pch = c(16, 17),
                 xlab = "Self vs Others",
                 ylab = "scale.3",
                 trace.label = "Harm Type")

summary(aov(scale.4 ~ SelfOthers * HarmType, data = Study2_clean))
Study2_clean %>%
  group_by(SelfOthers, HarmType) %>%
  summarise(
    Mean = mean(scale.4, na.rm = TRUE),
    SD = sd(scale.4, na.rm = TRUE),
    n = n()
  )
interaction.plot(x.factor = Study2_clean$SelfOthers,
                 trace.factor = Study2_clean$HarmType,
                 response = Study2_clean$scale.4,
                 fun = mean,
                 type = "b",
                 col = c("blue", "red"),
                 pch = c(16, 17),
                 xlab = "Self vs Others",
                 ylab = "scale.4",
                 trace.label = "Harm Type")


# below is my new manipulation check. runing a lot one way anova. 

Study2_clean$SelfOthers <- factor(Study2_clean$SelfOthers,
                                  levels = c(1, 2),
                                  labels = c("Self", "Others"))
Study2_clean$HarmType <- factor(Study2_clean$HarmType,
                                levels = c(1, 2),
                                labels = c("Reduce", "Cause"))

# Create a new variable for combined condition
Study2_clean$Condition <- interaction(Study2_clean$SelfOthers, Study2_clean$HarmType, sep = "_")

# Run four one-way ANOVAs
names(Study2_clean)

anova1 <- aov(scale.1 ~ Condition, data = Study2_clean)
Study2_clean %>%
  group_by(Condition) %>%
 dplyr:: summarise(
    Mean = mean(scale.1, na.rm = TRUE),
    SD = sd(scale.1, na.rm = TRUE),
    n =n()
    )


anova2 <- aov(scale.2 ~ Condition, data = Study2_clean)
Study2_clean %>%
  group_by(Condition) %>%
  dplyr:: summarise(
    Mean = mean(scale.2, na.rm = TRUE),
    SD = sd(scale.2, na.rm = TRUE),
    n = n()
  )

anova3 <- aov(scale.3 ~ Condition, data = Study2_clean)
Study2_clean %>%
  group_by(Condition) %>%
   dplyr::summarise(
    Mean = mean(scale.3, na.rm = TRUE),
    SD = sd(scale.3, na.rm = TRUE),
    n = n()
  )

anova4 <- aov(scale.4 ~ Condition, data = Study2_clean)
Study2_clean %>%
  group_by(Condition) %>%
   dplyr::summarise(
    Mean = mean(scale.4, na.rm = TRUE),
    SD = sd(scale.4, na.rm = TRUE),
    n = n()
  )

summary(anova1)
summary(anova2)
summary(anova3)
summary(anova4)



#Do people who perceive more harm (to self or others) rate the decision as more morally wrong?
cor.test(Study2_clean$scale.1, Study2_clean$scale.5)
cor.test(Study2_clean$scale.3, Study2_clean$scale.5) # these two negatively correlated with moral wrongness rating, which makes sense. 

cor.test(Study2_clean$scale.2, Study2_clean$scale.5)
cor.test(Study2_clean$scale.4, Study2_clean$scale.5) # these two positively correlated wiht moral wrongness rating, which also makes sense. 


# multi-collinearity check
cor.test(Study2_clean$scale.1, Study2_clean$scale.3)
cor.test(Study2_clean$scale.2, Study2_clean$scale.4)


```


```{r plot mean difference}

library(ggplot2)
library(dplyr)
summary_df <- Study2_clean %>%
  group_by(Condition) %>%
  summarise(
    Mean = mean(scale.1, na.rm = TRUE),
    SD = sd(scale.1, na.rm = TRUE),
    N = n(),
    SE = SD / sqrt(N)
  )

# Bar plot with error bars
ggplot(summary_df, aes(x = Condition, y = Mean, fill = Condition)) +
  geom_bar(stat = "identity", color = "black", width = 0.7) +
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE), width = 0.2) +
  labs(
    x = "Condition",
    y = "Mean Rating",
    title = "Mean Perceived Harm by Condition"
  ) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none")

```

